
import React from 'react';
import { Copy, Database, CheckCircle2 } from 'lucide-react';

interface Props {
  onClose: () => void;
}

const SupabaseSetupInstructions: React.FC<Props> = ({ onClose }) => {
  const [copied, setCopied] = React.useState(false);

  const sqlCode = `
-- 1. Bảng Nhân Viên (Employees)
create table if not exists public.employees (
  id text primary key,
  "fullName" text,
  role text,
  phone text,
  degree text,
  age int4,
  password text
);
alter table public.employees enable row level security;
create policy "Enable all access" on public.employees for all using (true);

-- 2. Bảng Khách Hàng (Customers)
create table if not exists public.customers (
  id text primary key,
  "fullName" text,
  phone text,
  "medicalHistory" text,
  age int4,
  address text,
  "relativeInfo" text,
  "loyaltyPoints" int4 default 0,
  "lastPurchaseDate" text
);
alter table public.customers enable row level security;
create policy "Enable all access" on public.customers for all using (true);

-- 3. Bảng Hóa Đơn (Sales Invoices)
create table if not exists public.sales_invoices (
  id text primary key,
  date text,
  "customerId" text,
  "customerName" text,
  "customerPhone" text,
  "employeeId" text,
  "employeeName" text,
  "totalAmount" numeric,
  "totalTax" numeric,
  "totalProfit" numeric,
  "paymentMethod" text,
  "storeId" text,
  "totalItems" int4,
  "pointsEarned" int4,
  "pointsRedeemed" int4,
  "discountAmount" numeric
);
alter table public.sales_invoices enable row level security;
create policy "Enable all access" on public.sales_invoices for all using (true);

-- 4. Bảng Chi Tiết Hóa Đơn (Invoice Details)
create table if not exists public.invoice_details (
  id text primary key,
  "invoiceId" text,
  "productId" text,
  quantity int4,
  "unitPrice" numeric,
  discount numeric,
  vat numeric
);
alter table public.invoice_details enable row level security;
create policy "Enable all access" on public.invoice_details for all using (true);

-- 5. Bảng Nhà Cung Cấp (Suppliers)
create table if not exists public.suppliers (
  id text primary key,
  name text,
  address text,
  phone text,
  "taxId" text,
  "countryId" text,
  type text
);
alter table public.suppliers enable row level security;
create policy "Enable all access" on public.suppliers for all using (true);

-- 6. Bảng Sản Phẩm (Products) - Cập nhật
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  ten_thuoc text,
  hoat_chat text,
  ham_luong text,
  dang_bao_che text,
  quy_cach_dong_goi text,
  don_vi_tinh text,
  gia_ban numeric,
  cong_ty text,
  nuoc_san_xuat text
);
alter table public.products enable row level security;
create policy "Enable all access" on public.products for all using (true);
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 bg-slate-900/80 z-[60] flex items-center justify-center p-4 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden animate-slide-up">
        <div className="p-6 border-b border-slate-100 flex items-center gap-4 bg-blue-50">
          <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center">
             <Database size={24} />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-800">Cấu Hình Cơ Sở Dữ Liệu</h2>
            <p className="text-sm text-slate-600">Phát hiện kết nối Supabase thành công nhưng chưa có bảng dữ liệu.</p>
          </div>
        </div>
        
        <div className="p-6 overflow-y-auto flex-1 custom-scrollbar">
          <p className="mb-4 text-slate-600 text-sm">
            Hệ thống không tìm thấy các bảng cần thiết (<code>employees</code>, <code>sales_invoices</code>...). 
            Vui lòng sao chép đoạn mã SQL dưới đây và chạy trong 
            <a href="https://supabase.com/dashboard/project/_/sql" target="_blank" rel="noreferrer" className="text-blue-600 font-bold hover:underline mx-1">
              Supabase SQL Editor
            </a> 
            để khởi tạo.
          </p>

          <div className="relative group">
            <pre className="bg-[#1e293b] text-blue-100 p-4 rounded-xl text-xs overflow-x-auto font-mono leading-relaxed border border-slate-700 shadow-inner max-h-80">
              {sqlCode}
            </pre>
            <button 
              onClick={handleCopy}
              className="absolute top-2 right-2 bg-white/10 hover:bg-white/20 text-white p-2 rounded-lg transition-all opacity-0 group-hover:opacity-100"
              title="Sao chép SQL"
            >
              {copied ? <CheckCircle2 size={16} className="text-emerald-400"/> : <Copy size={16} />}
            </button>
          </div>
        </div>

        <div className="p-4 border-t border-slate-100 bg-slate-50 flex justify-end gap-3">
          <button 
             onClick={onClose}
             className="px-6 py-2 bg-gradient-to-r from-[#0047AB] to-[#1E5FD6] text-white font-bold rounded-xl hover:shadow-lg hover:shadow-blue-500/30 transition-all active:scale-95"
          >
            Đã Chạy SQL Xong (Tải Lại)
          </button>
        </div>
      </div>
    </div>
  );
};

export default SupabaseSetupInstructions;
